---
- name: Add prometheus user
  hosts: all
  become: true
  remote_user: admin
  gather_facts: false
  tags: 'Done'

  tasks:
    - name: Add group
      ansible.builtin.group:
        name: "prometheus"
        state: present
        system: true

    - name: Add user
      ansible.builtin.user:
        name: "prometheus"
        group: "prometheus"
        create_home: false
        system: true
        state: present

- name: Install Prometheus server
  hosts: prometheus_server
  become: true
  remote_user: admin
  gather_facts: false
  tags: 'Done'

  tasks:

    - name: Download and unpack
      ansible.builtin.unarchive:
        remote_src: true
        src: "https://github.com/prometheus/prometheus/releases/download/v2.42.0/prometheus-2.42.0.linux-386.tar.gz"
        dest: "/home/admin/"
        owner: 'admin'
        group: 'admin'

    - name: Check dirs
      ansible.builtin.file:
        path: '{{ item }}'
        state: directory
        owner: "prometheus"
        group: 'prometheus'
        mode: '755'
        recurse: true
      loop:
        - "/etc/prometheus"
        - "/var/lib/prometheus"

    - name: Copy files to bin
      ansible.builtin.copy:
        remote_src: true
        src: '{{ item }}'
        dest: "/usr/local/bin/"
        owner: 'prometheus'
        group: 'prometheus'
        mode: '744'
      loop:
        - "/home/admin/prometheus-2.42.0.linux-386/prometheus"
        - "/home/admin/prometheus-2.42.0.linux-386/promtool"

    - name: Copy prometheus config file
      ansible.builtin.copy:
        src: "./prometheus.yml"
        dest: "/etc/prometheus/"
        owner: 'prometheus'
        group: 'prometheus'
        mode: '755'

    - name: Copy dirs
      ansible.builtin.copy:
        remote_src: true
        src: '{{ item }}'
        dest: "/etc/prometheus/"
        owner: 'prometheus'
        group: 'prometheus'
        mode: '755'
      loop:
        - "/home/admin/prometheus-2.42.0.linux-386/console_libraries"
        - "/home/admin/prometheus-2.42.0.linux-386/consoles"

- name: Setup prometheus
  hosts: prometheus_server
  become: true
  remote_user: admin
  gather_facts: false

  tasks:

    - name: Copy service
      ansible.builtin.copy:
        src: './prometheus.service'
        dest: '/etc/systemd/system/prometheus.service'
        mode: '744'

    - name: Enable and restart
      ansible.builtin.systemd:
        name: 'prometheus'
        state: restarted
        enabled: true

    - name: Check Prometheus
      ansible.builtin.uri:
        url: 'http://localhost:9090'
        status_code:
          - '200'

- name: Install NodeExplorer
  hosts: all
  become: true
  remote_user: admin
  gather_facts: false
  tags: 'Done'

  tasks:

    - name: Download NodeExplorer
      ansible.builtin.unarchive:
        remote_src: true
        src: 'https://github.com/prometheus/node_exporter/releases/download/v1.4.0/node_exporter-1.4.0.linux-amd64.tar.gz'
        dest: '/home/admin/'

    - name: 'Make dir'
      ansible.builtin.file:
        path: '/etc/prometheus/node_exporter'
        state: directory
        owner: prometheus
        group: prometheus
        mode: '755'

    - name: 'Copy bin'
      ansible.builtin.copy:
        remote_src: true
        src: '/home/admin/node_exporter-1.4.0.linux-amd64/'
        dest: '/etc/prometheus/node_exporter/'
        owner: prometheus
        group: prometheus
        mode: '755'

- name: Setup node_exporter
  hosts: all
  become: true
  remote_user: admin
  gather_facts: false

  tasks:

    - name: Copy service
      ansible.builtin.copy:
        src: './node_exporter.service'
        dest: '/etc/systemd/system/node_exporter.service'
        owner: prometheus
        group: prometheus
        mode: '744'

    - name: Enable and restart
      ansible.builtin.systemd:
        name: 'node_exporter'
        state: restarted
        enabled: true

    - name: Check NodeExplorer
      ansible.builtin.uri:
        url: 'http://localhost:9100'
        status_code:
          - '200'
